language: python
cache: pip

sudo: false
dist: trusty
addons:
  apt:
    packages:
      - libxml2-utils
      
before_install:
  - chmod +x build.sh

install:
  - cd exitwp
  - pip install --upgrade -r pip_requirements.txt

before_script:
- chmod a+x ./build.sh

script:
  - ../build.sh
